# Generated by Django 3.2.4 on 2021-07-07 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPanda', '0002_auto_20210618_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idMoneda', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Moneda')),
                ('MonedaDePago', models.CharField(max_length=15, verbose_name='Pesos o Dólares')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('NumeroId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de identificación')),
                ('fotoLogoP', models.ImageField(null=True, upload_to='Fotografía/logo del proveedor')),
                ('NombreC', models.CharField(max_length=40, verbose_name='Nombre Completo del Proveedor')),
                ('Telefono', models.IntegerField(verbose_name='Número telefonico')),
                ('Direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('Email', models.CharField(max_length=30, verbose_name='Email')),
                ('Pais', models.CharField(max_length=15, verbose_name='País')),
            ],
        ),
        migrations.DeleteModel(
            name='ComentarioC',
        ),
        migrations.DeleteModel(
            name='Resenna',
        ),
        migrations.AddField(
            model_name='moneda',
            name='MonedaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPanda.registro'),
        ),
    ]
