# Generated by Django 3.2.4 on 2021-07-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPanda', '0003_auto_20210706_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fotoLogoP',
            field=models.ImageField(null=True, upload_to='Fotografía/logo del proveedor', verbose_name='Fotografía/logo del proveedor'),
        ),
    ]
