# Generated by Django 3.2.4 on 2021-07-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPanda', '0004_alter_registro_fotologop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moneda',
            new_name='TipoMoneda',
        ),
    ]
