# Generated by Django 3.2.4 on 2021-07-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPanda', '0005_rename_moneda_tipomoneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomoneda',
            name='MonedaPago',
        ),
    ]
